# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# install only production dependencies
COPY package*.json ./
RUN npm install --production

# copy source
COPY . .

# default command
CMD ["node", "nano-currency.js"]
